/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32l476xx.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay()
{
	for(int i=0;i<100000;i++);

}
int main(void)
{
    /* Loop forever */
	GPIO_Handle_T *gpioled;
	memset(&gpioled,0,sizeof(gpioled));
	gpioled->pGPIOx=GPIOA;
	gpioled->pGPIOM.GPIO_PIN=GPIO_PIN_NUM5;
	gpioled->pGPIOM.GPIO_MODE=OUTPUT_MODE;
	gpioled->pGPIOM.GPIO_OUTTYPE=OUTPUT_PUSHPULL;
	gpioled->pGPIOM.GPIO_PUPDM=PUSHPULL_NOPUPD;
	gpioled->pGPIOM.GPIO_SPEED=SPEED_LS;



	//for user button at PC13

	GPIO_Handle_T *gpiobutton;
	memset(&gpiobutton,0,sizeof(gpiobutton));
		gpiobutton->pGPIOx=GPIOC;
		gpiobutton->pGPIOM.GPIO_PIN=GPIO_PIN_NUM13;
		gpiobutton->pGPIOM.GPIO_MODE=INPUT_MODE;
		gpiobutton->pGPIOM.GPIO_OUTTYPE=OUTPUT_PUSHPULL;
		gpiobutton->pGPIOM.GPIO_PUPDM=PUSHPULL_PU;
		gpiobutton->pGPIOM.GPIO_SPEED=SPEED_LS;
	//first enable the clock for gpio

	GPIO_PERI_CLK(GPIOA,ENABLE);
    GPIO_INIT(&gpioled);

    GPIO_PERI_CLK(GPIOC,ENABLE);
    GPIO_INIT(&gpiobutton);

    IRQInterruptEnable(EXTI15_10,ENABLE);
    IRQPrioritySet(EXTI15_10,15);

	while(1)
	{

	}
}
void EXTI15_10_IRQHandler(void)
{
	IRQHandling(gpiobutton->pGPIOM.GPIO_PIN);
	GPIO_PIN_TOGGLE(&gpioled,gpioled->pGPIOM.GPIO_PIN);
}
